/* This file is auto-generated by SST. Do not edit. */
/* tslint:disable */
/* eslint-disable */
/* deno-fmt-ignore-file */
/* biome-ignore-all lint: auto-generated */

declare module "sst" {
  export interface Resource {
    "SECRETS": {
      "type": "sst.sst.Secret"
      "value": string
    }
    "SECRETS_SHARED": {
      "type": "sst.sst.Secret"
      "value": string
    }
    "bucket": {
      "name": string
      "type": "sst.aws.Bucket"
    }
    "email": {
      "configSet": string
      "sender": string
      "type": "sst.aws.Email"
    }
    "tbl-api-keys": {
      "name": string
      "type": "sst.aws.Dynamo"
    }
    "tbl-bal-txs": {
      "name": string
      "type": "sst.aws.Dynamo"
    }
    "tbl-balances": {
      "name": string
      "type": "sst.aws.Dynamo"
    }
    "tbl-banking-apps": {
      "name": string
      "type": "sst.aws.Dynamo"
    }
    "tbl-commissions": {
      "name": string
      "type": "sst.aws.Dynamo"
    }
    "tbl-don-msgs": {
      "name": string
      "type": "sst.aws.Dynamo"
    }
    "tbl-dons": {
      "name": string
      "type": "sst.aws.Dynamo"
    }
    "tbl-dons-settled": {
      "name": string
      "type": "sst.aws.Dynamo"
    }
    "tbl-endowments": {
      "name": string
      "type": "sst.aws.Dynamo"
    }
    "tbl-forms": {
      "name": string
      "type": "sst.aws.Dynamo"
    }
    "tbl-funds": {
      "name": string
      "type": "sst.aws.Dynamo"
    }
    "tbl-liquid": {
      "name": string
      "type": "sst.aws.Dynamo"
    }
    "tbl-main": {
      "name": string
      "type": "sst.aws.Dynamo"
    }
    "tbl-metrics": {
      "name": string
      "type": "sst.aws.Dynamo"
    }
    "tbl-nav-history": {
      "name": string
      "type": "sst.aws.Dynamo"
    }
    "tbl-payouts-v2": {
      "name": string
      "type": "sst.aws.Dynamo"
    }
    "tbl-registrations": {
      "name": string
      "type": "sst.aws.Dynamo"
    }
    "tbl-subs": {
      "name": string
      "type": "sst.aws.Dynamo"
    }
    "tbl-summary": {
      "name": string
      "type": "sst.aws.Dynamo"
    }
    "tbl-users": {
      "name": string
      "type": "sst.aws.Dynamo"
    }
    "tbl-users-meta": {
      "name": string
      "type": "sst.aws.Dynamo"
    }
    "tbl-webhooks": {
      "name": string
      "type": "sst.aws.Dynamo"
    }
    "usrpl": {
      "id": string
      "type": "sst.aws.CognitoUserPool"
    }
    "website": {
      "type": "sst.aws.React"
      "url": string
    }
  }
}
/// <reference path="sst-env.d.ts" />

import "sst"
export {}