import type { INpo } from "./schema";

export const npo_fields: { [K in keyof Required<INpo>]: "" } = {
  id: "",
  active_in_countries: "",
  endow_designation: "",
  fiscal_sponsored: "",
  hide_bg_tip: "",
  hq_country: "",
  image: "",
  kyc_donors_only: "",
  logo: "",
  name: "",
  overview: "",
  published: "",
  registration_number: "",
  social_media_urls: "",
  sdgs: "",
  street_address: "",
  tagline: "",
  url: "",
  slug: "",
  keyword: "",
  claimed: "",
  card_img: "",
  progDonationsAllowed: "",
  allocation: "",
  donateMethods: "",
  increments: "",
  receiptMsg: "",
  fund_opt_in: "",
  env: "",
  target: "",
  referrer: "",
  referrer_expiry: "",
  referral_id: "",
  w_form: "",
  payout_minimum: "",
  donor_address_required: "",
  donate_frequencies: "",
};
